--- #YAML:1.0
name:         TemplateM
version:      3.00
version_from: TemplateM.pm
abstract:     TemplateM - *ML templates processing module 
author:
    - Lepenkov Sergey (Serz Minus), C<minus@mail333.com>
installdirs:  perl
requires:
    File::Spec:      0.82
    LWP:             5.80
    LWP::UserAgent:  5.80
    HTTP::Headers:   5.80
    HTTP::Request:   5.80
    HTTP::Response:  5.80
distribution_type: module
configure_requires:
    ExtUtils::MakeMaker: 6.40
build_requires:
    ExtUtils::MakeMaker: 6.40
    Test::More:          0.80
generated_by: ExtUtils::MakeMaker version 6.40
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
license: perl
