---
abstract: '*ML templates processing module '
author:
  - 'Lepenkov Sergey (Serz Minus) <minus@mail333.com>'
build_requires:
  ExtUtils::MakeMaker: 6.6
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TemplateM
no_index:
  directory:
    - t
    - inc
recommends:
  Data::Dumper: 0
  URI: 1.6
requires:
  ExtUtils::MakeMaker: 6.6
  File::Spec: 0.82
  HTTP::Headers: 5.8
  HTTP::Request: 5.8
  HTTP::Response: 5.8
  LWP: 5.8
  LWP::MediaTypes: 6
  LWP::UserAgent: 5.8
  Test::More: 0.94
  URI: 1.6
  perl: 5.008001
resources:
  homepage: http://www.serzik.ru
  license: http://dev.perl.org/licenses/
  repository: https://svn.code.sf.net/p/templatem/code/
version: 3.02
